name: CI
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint-and-build:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint App
        run: yarn lint
      - name: Type Check App
        run: yarn tsc
  call-vercel:
    name: Call Vercel build workflow
    needs: lint-and-build
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-vercel.yml@main
    secrets: inherit
  call-docker:
    name: Call Docker build workflow
    needs: lint-and-build
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-docker.yml@main
    secrets: inherit
