name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"

jobs:
  lint-and-build:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    permissions:
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint App
        run: yarn lint --output-file eslint_report.json --format json
        continue-on-error: true
      - name: Type Check App
        run: yarn tsc > typescript.log
        continue-on-error: true
      - uses: DerLev/eslint-annotations@v1
        with:
          eslint-report: eslint_report.json
          typescript-log: typescript.log
          error-on-warn: true
  call-vercel:
    name: Call Vercel build workflow
    needs: lint-and-build
    if: github.event_name == 'push'
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-vercel.yml@main
    secrets: inherit
  call-docker-production:
    name: Call Docker prod build workflow
    needs: lint-and-build
    if: github.event_name == 'push'
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-docker-production.yml@main
    secrets: inherit
  call-docker-development:
    name: Call Docker dev build workflow
    needs: lint-and-build
    if: github.event_name == 'pull_request'
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-docker-development.yml@main
    secrets: inherit
