name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint-and-build:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint App
        run: yarn lint --output-file eslint_report.json --format json
        continue-on-error: true
      - name: Annotate Code
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint_report.json
          only-pr-files: false
      - name: Type Check App
        run: yarn tsc
  call-vercel:
    name: Call Vercel build workflow
    needs: lint-and-build
    if: github.ref == 'refs/heads/main'
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-vercel.yml@main
    secrets: inherit
  call-docker:
    name: Call Docker build workflow
    needs: lint-and-build
    uses: DerLev/mcmineserver-2023/.github/workflows/deployment-docker.yml@main
    secrets: inherit
